// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Music.DbMigrator;

#nullable disable

namespace Music.DbMigrator.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20240206083814_changeNUll")]
    partial class changeNUll
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Music.DbMigrator.Domain.FaithUser", b =>
                {
                    b.Property<long>("id")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("isdel")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<string>("passWord")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("userAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("m_user", (string)null);
                });

            modelBuilder.Entity("Music.DbMigrator.Domain.MusicInfo", b =>
                {
                    b.Property<long>("id")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<string>("arr02")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("arr03")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("createBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("createTime")
                        .HasMaxLength(50)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("isDel")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("musicAlbum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("musicComposer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("musicDuration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("musicName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("musicSingerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("musicStar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("musicUrl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("updateBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updateTime")
                        .HasMaxLength(50)
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("m_music_info", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
